### ISSUE TITLE
Copyright is repeated

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/amoeba-frontpages#27]
In footer in mobile view:
![Capture](https://user-images.githubusercontent.com/32234926/82746910-6c9a1c00-9db2-11ea-9249-b5a8a0473337.JPG)

**Comment by Yogita98** [comment]
@abhishek97 Can you assign me this issue?

**Comment by nikunjdk** [comment]
I would like to be assigned to it. Thank you.

**Comment by kanak54** [comment]
Is this issue still open?
