### ISSUE TITLE
icons are not being loaded- attaching  screenshot 

### ISSUE THREAD

**Issue by maheshoz** [coding-blocks/amoeba-frontpages#4]
![image](https://user-images.githubusercontent.com/35638589/82082918-7b276a00-9706-11ea-91c6-fe6a8ae57693.png)

![image](https://user-images.githubusercontent.com/35638589/82083041-b033bc80-9706-11ea-8a1a-8fe197bc4ea5.png)

**Comment by abhishek97** [comment]
Thanks for pointing it out. Fixed now. This was due to issue in our production infra and not source code bug.

**Comment by maheshoz** [comment]
And also an icon in footer is not loaded..

screenshot:
![image](https://user-images.githubusercontent.com/35638589/82195272-b2b83100-9915-11ea-801d-07dfed6d5e65.png)
