### ISSUE TITLE
No scrolling to view the learning tracks on desktops

### ISSUE THREAD

**Issue by maheshoz** [coding-blocks/amoeba-frontpages#6]
we can scroll and view the learning tracks on mobile and tablet devices but on desktops it is not possible.

![image](https://user-images.githubusercontent.com/35638589/82122639-6b655f80-97b2-11ea-9c03-6363b454730e.png)

Also there is no margin for popular courses section on mobile and tablet screen sizes.

![image](https://user-images.githubusercontent.com/35638589/82122708-c8611580-97b2-11ea-8e9b-47ba1747a774.png)

**Comment by abhishek97** [comment]
Accepted and added Boss labels
