### ISSUE TITLE
online.codingblocks.com hangs sometimes when pre-logged in!

### ISSUE THREAD

**Issue by githubdkg** [coding-blocks/amoeba-frontpages#7]
![CBOnline_error](https://user-images.githubusercontent.com/44174331/82123086-0b23ed00-97b5-11ea-895a-c67eac621f7d.jpg)

Occasionally, when pre logged in, frontpage do not loads up and forcefully hangs all other tabs too. Browser needs to be closed as a result.

Source details:
Browser: Chrome
OS: Windows 10

**Comment by abhishek97** [comment]
@githubdkg are you able to reproduce this?

**Comment by githubdkg** [comment]
Yes! Here it is. As always, all tabs need to be closed from task manager.

![image](https://user-images.githubusercontent.com/44174331/82180120-82649880-98fd-11ea-94a3-eb6c04363082.png)

**Comment by githubdkg** [comment]
@abhishek97

**Comment by abhishek97** [comment]
What are the steps to reproduce? List down what needs to be done to get this state

**Comment by githubdkg** [comment]
1. Login to online.codingblocks.com (with username and password) after checking "Remember me" button. Close the browser.
2. Jump directly to address bar and type online.codingblocks.com. Press enter. At this point, the page hangs up occasionally. If not, close browser, and repeat step 2.
I have experienced this problem only in Desktop (Google Chrome | Windows 10 x64).

**Comment by githubdkg** [comment]
@abhishek97

**Comment by githubdkg** [comment]
@abhishek97

**Comment by abhishek97** [comment]
Sorry I missed this. Will test this tomorrow

**Comment by githubdkg** [comment]
@abhishek97

**Comment by abhishek97** [comment]
@githubdkg I am not able to reproduce the above steps. Can you share video of this? also check console and network for errors/failed requests

**Comment by githubdkg** [comment]
@abhishek97 Sir I can't share the video as the page only stucks sometimes. You will see it after repeated trials(maximum 4); steps for which are shared earlier.

**Comment by githubdkg** [comment]
Sir, how can I check for failed requests?
